spring:
  application:
    name: order-service
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderservice
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
